#server:
#  servlet:
#    application-display-name: /demo

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true

#logging:
#  config: classpath:logback-spring.xml